run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 10
